### ISSUE TITLE
Automatically register ProjectionCommit contract

### ISSUE THREAD

**Issue by mgressman-marketvision** [Elders/Cronus#102]
We need to automatically register ProjectionCommit contract like we do for AggregateCommit

Currently we do it manually and it creates a lot of confusion:
```
.UseContractsFromAssemblies(new System.Reflection.Assembly[]
                    {
                    typeof(ProjectionCommit).Assembly})
```

**Comment by mynkow** [comment]
@Sinstraliz I think you fixed this at some point. Confirm?

**Comment by Sinstraliz** [comment]
@mynkow yes this is fixed I am closing this.
