### ISSUE TITLE
Endpoint to explore the current Domain

### ISSUE THREAD

**Issue by mynkow** [Elders/Cronus#138]
This should inspect all assemblies and look for a types which implement `ICommand` interface. The result will be a list of all types with their `DataContract.Name` and the type name.

See how we do similar thing when [getting the projections](https://github.com/Elders/Cronus.Api/blob/master/src/Elders.Cronus.Api/Controllers/ProjectionMetaController.cs#L33). 

NOTE: The only thing which concerns me is the usage of `AppDomain`.

**Comment by tokmac** [comment]
The work is finished in branch 'feature-138' but currently cant be tested before #140 is finished.

**Comment by mynkow** [comment]
I am rethinking how we are approaching this. It will be better if we get all domain commands, events and aggregates with a single API call. The relations between them have to be described as well.

In the API project we can create a class `DomainExplorer` to fulfill these needs.

The end result may look like something like the screenshot:
![image](https://user-images.githubusercontent.com/183151/68044404-ee740c00-fcdf-11e9-91cd-dd15e0f94a09.png)
