### ISSUE TITLE
Replace LibLog with dotnet core logger

### ISSUE THREAD

**Issue by mynkow** [Elders/Cronus#188]
Thank you LibLog

https://github.com/damianh/LibLog/issues/270

---

List of repositories which we need to update:
- [x] Cronus.DomainModeling - This dosn't use LibLog
- [x] Cronus
- [x] Cronus.Transport.RabbitMQ
- [x] Cronus.Persistence.Cassandra
- [x] Cronus.Projections.Cassandra
- [x] Cronus.AspNetCore - has no logging
- [x] Cronus.AtomicAction.Redis
- [x] Cronus.Serialization.NewtonsoftJson
- [x] Cronus.Cluster.Consul - has no logging
- [x] Cronus.Api

**Comment by damianh** [comment]
You're welcome, it was a good run :)

**Comment by mynkow** [comment]
We need to figure out how we are going to do static logging (logging during application startup where the DI container is not yet initialized). We need to consider an abstraction without adding a dependency to a logger.

**Comment by mynkow** [comment]
@ethno2405 I have created a list of all repositories where we need to update the logger.

**Comment by ethno2405** [comment]
@mynkow All repos are updated. Closing.
