### ISSUE TITLE
Cronus Sample throws an exception

### ISSUE THREAD

**Issue by ethno2405** [Elders/Cronus#230]
This SimpleSample project throws an exception ``'Unable to resolve service for type 'Elders.Cronus.TypeContainer`1[Elders.Cronus.EventStore.Index.IEventStoreIndex]' while attempting to activate 'Elders.Cronus.EventStoreIndicesStartup'.'`` on startup.

**Comment by mynkow** [comment]
@ethno2405 is this fixed now?
