### ISSUE TITLE
Urn.Parse() returns the wrong type

### ISSUE THREAD

**Issue by mynkow** [Elders/Cronus#235]
Right now the parse method of the `Urn` class returns IUrn.

[`public static IUrn Parse(string urn, IUrnFormatProvider proviver)`](https://github.com/Elders/Cronus.DomainModeling/blob/master/src/Elders.Cronus.DomainModeling/Urn.cs#L205)

It seems wrong to return the super type instead of the current type because implicitly `Urn` could be casted to `IUrn` but not vice versa.

Do you think it is reasonable to change the signature of the Parse?

**Comment by mynkow** [comment]
Actually, this is a regression. I will roll it back as it was in previous version (5.2.2)

**Comment by mynkow** [comment]
Fixed in https://github.com/Elders/Cronus.DomainModeling/commit/f39b66668393bc01af33d524f19b541a51000dd4

**Comment by tokmac** [comment]
I agree because currently this _Parse_ method is not defined by the interface, but by the Urn class as a static method. This gives a clue that if somebody uses it, it is more likely he/she needs the result as an exact type.

**Comment by ethno2405** [comment]
Not sure why you would need the `IUrn` interface at all. There is only one urn RFC. The interface does not declare any actions, only requires you to expose certain data from your implementation. If you want to allow someone to change the Urn logic (only parsing in this case), just make the methods virtual.
