### ISSUE TITLE
Dev guide documentation

### ISSUE THREAD

**Issue by ethno2405** [Elders/Cronus#245]
Research and propose tools for creating good looking documentation.

**Comment by tokmac** [comment]
Some hints what to do after this issue: https://opensource.com/article/20/3/documentation

**Comment by tokmac** [comment]
[GitBook](https://www.gitbook.com/) is providing a PaaS for creating, managing, and hosting documentation. Their service is paid but they claim that they could offer the platform for free to open source projects. I have created a request which is still in the waiting process. Will add more info in a few days no mater we have a positive or no answer from them

**Comment by tokmac** [comment]
Another possible solution which could be used is to create manually the documentation in Md (in a dedicated repo) and then using [ReadTheDocs] (https://readthedocs.org/) to host the documentation

**Comment by tokmac** [comment]
We will start with the ReadTheDocs approach and after that, we can reconsider using GitBook if they provide us free access.
