### ISSUE TITLE
Setup ReadTheDocs integration with Cronus repo

### ISSUE THREAD

**Issue by tokmac** [Elders/Cronus#247]
#245 
We need to have a hosted simple "Hello Doc" page hosted on ReadTheDocs domain

**Comment by tokmac** [comment]
[Here](https://elders-cronus.readthedocs.io/en/latest/) is hosted website of the documentation.

**Comment by tokmac** [comment]
@mynkow, please signup in [ReadTheDocs](https://readthedocs.org/) in order to add you as a maintainer

**Comment by mynkow** [comment]
@tokmac done

**Comment by mynkow** [comment]
I am closing this because we are moving with gitbook
