### ISSUE TITLE
Define high-level structure for the documentation

### ISSUE THREAD

**Issue by tokmac** [Elders/Cronus#248]
[Axon ](https://github.com/AxonFramework/AxonFramework) is the twin brother of Cronus in the Java world. It has awsome documentation from which we could borrow the structure.

**Comment by tokmac** [comment]
@abuijze, do you mind borrowing some parts of the documentation structure you and your team have provided for Axon

**Comment by mynkow** [comment]
The initial structure is done. If we have a better idea we will change it.
