### ISSUE TITLE
The Discord invite link is invalid

### ISSUE THREAD

**Issue by jeffward01** [Elders/Cronus#334]
Looks like a very great framework! I wanted to learn more in the Discord (i'm currently reading the docs) - and I saw that the Discord Invite was broken.

Here is the link:  https://discord.gg/2wbN8kt 

Thanks!

**Comment by ethno2405** [comment]
Thanks for pointing that out! The Discord link is now valid. Happy coding!

**Comment by mynkow** [comment]
@jeffward01 the docs are up to date but are not complete. I will be happy to provide any information, write more docs or provide samples if you need something specific.
