### ISSUE TITLE
Ability to track commands and events with CorrelationId and CausationId

### ISSUE THREAD

**Issue by sdluxeon** [Elders/Cronus#77]
The correlation id is created whenever a command enters the system. All the events and the following raised commands inherit the on top parent command correlation id. The correlation id is different than the command id.
http://msdn.microsoft.com/en-us/library/system.diagnostics.correlationmanager%28v=vs.110%29.aspx

**Comment by SayliS** [comment]
Ideally there are 3 Ids for a message

* MessageId - the message ID. this is simple
* CorrelationId - this is something like context ID. You 
copy the correlationId of the message you are responding to to your 
message.
* CausationId - The CausationId of your message is the MessageId of the 
message you are responding to.

**Comment by sdluxeon** [comment]
This is good to be implemented using a ReporterAction and plug it using configuration to the flow control described in #98
