### ISSUE TITLE
Add concept for IGateway ports

### ISSUE THREAD

**Issue by sdluxeon** [Elders/Cronus#84]
We have ports that are throwing commands. Which is ok if we send commands to the same BC, but there is a need to have ports with state(aka IGateway) for external BC like push notifications,emails etc. There is no need to event source this state and its perfectly fine if this state is wiped. Example: iOS push notifications badge.This state should be used only for infrastructure need and never for business cases. 

NM: Usually projections just track events and project their data. They are not allowed to send any commands at all. However generic domains such as emailing, notification services etc. require explicit invocation of their APIs with some meta data attached. Basically we need to store and track this metadata inside `IGateway` state. Also, `IGateway` are restricted and not touched when events are replayed.

**Comment by mynkow** [comment]
Currently we have similar concept in mind described in #92 for Saga support. However these must be separate because `IGateway` should not be event sourced.
